[project]
name = "ticket-classifier-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.2",
    "langchain-core>=1.6.4",
    "langchain-openai>=1.6.3",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ticket-classifier-project = "ticket_classifier_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
